name: Publish to NPM

on:
  release:
    types: [published, edited]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Setup Node 
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Prepare workspace
        run: |
          rm -rf .vscode .github
          npm install
          npm test

      - name: Publish to NPM
        if: success()
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          dry-run: false